config/routes.rb
Rails.application.routes.draw do
  resources :forums, only: [:index, :show, :new, :create]
  resources :posts, only: [:show, :new, :create], path: '/forums/:forum_id/'
  
  root to: 'forums#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :forum
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @posts = @forum.posts.all.order("updated_at DESC")
    byebug
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      redirect_to forums_path
    else
      render 'new'
    end
  end

  private
  def forum_params
    params.require(:forum).permit(:name, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_forum, only: [:show, :new, :create]

  def show
    @post = @forum.posts.find_by(forum_id: @forum.id, id: params[:id])
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.forum_id = params[:forum_id]
    byebug
    if @post.save
      redirect_to post_path(params[:forum_id], @post)
    else
      render 'new'
    end
  end

  private
  def set_forum
    @forum = Forum.find(params[:forum_id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :forum_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/forums/index.html.erb
<div class='container'>
  <%# <h1 class='title'>Forums</h1> %>
  <hr />
  <%= button_to "Create new Forum", new_forum_path, method: :get, class: "button" %>
  <% if @forums.size == 0 %>
    <p>Nothing here!</p>
  <% else %>
    <% @forums.each do |forum| %>
      <div class='card forum-card'>
        <div class='card-content'>
          <div class='columns'>
            <div class='column is-four-fifths'>
              <p class='forum-title'><%= forum.name %></p>
              <p><%= forum.description %></p>
            </div>
            <div class='column'>
              <%= link_to 'Visit >>', forum, class: 'visit-forum-link' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/forums/new.html.erb
<div class='container'>
  <h1 class='title'>New Forum</h1>
  <hr />
  <%= form_for @forum, html: { class: "new_forum_form" } do |f| %>
    <div class="field">
      <%= f.label :name, class: "label" %>
      <p class="help">What's the name of this new forum?</p>
      <div class="control">
        <%= f.text_field :name, class: "input" %>
      </div>
    </div>

    <div class="field">
      <%= f.label :description, class: "label" %>
      <p class="help">Make it something useful, will ya?</p>
      <div class="control">
        <%= f.text_field :description, class: "input" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.submit "Create", class: "button is-link" %>
      </div>
    </div>
  <% end %>

</div>

app/views/forums/show.html.erb
<div class='container'>
  <h1 class='title forum-title'><%= @forum.name %></h1>
  <p><%= @forum.description %></p>
  <hr />
  <%= button_to "Create new Post", new_post_path(@forum), method: :get, class: "button" %>
  <% if @posts.size == 0 %>
    <p>No posts here!</p>
  <% else %>
    <div class='forum-posts'>
      <% @posts.each do |post| %>
        <div class='card visit-post'>
          <div class='card-content'>
            <div class='columns'>
              <div class='column is-7'>
                <%= link_to post_path(@forum.id, post.id) do %>
                  <p class='post-title-link'><%= post.title %></p>
                <% end %>
              </div>
              <div class="column is-1">
                <%= fa_icon "comment", 
                  class: 'comment-bubble', 
                  text: post.comments.length if post.comments.length != 0 %>
              </div>
              <div class='column is-2'>
                <p>username</p>
              </div>
              <div class='column is-2'>
                <% if post.comments.blank? %>
                  <p><%= post.created_at.strftime("%m/%d/%y %H:%M") %></p>
                <% else %>
                  <p><%= post.comments.last.created_at.strftime("%m/%d/%y %H:%M") %></p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class='navbar' role='navigation'>
  <div class='navbar-brand'>
    <div class='navbar-item'>
      <p class='has-text-black'>Rails</p>
      <p class='has-text-link'>FAQS</p>
    </div>
  </div>
  <div class='navbar-menu'>
    <div class='navbar-start'>
      <%= link_to 'All Forums', forums_path, class: 'navbar-item' %>
    </div>
    <div class='navbar-end'>
      <p class='navbar-item'>Profile?</p>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsfaqs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class='content'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<div class='container'>
  <h1 class='title'>New Post in <%= @forum.name %></h1>
  <hr />
  <%= form_for @post, html: { class: "new_post_form" } do |f| %>
    <div class="field">
      <%= f.label :title, class: "label" %>
      <p class="help">What's the title of your post?</p>
      <div class="control">
        <%= f.text_field :title, class: "input" %>
      </div>
    </div>

    <div class="field">
      <%= f.label :content, class: "label" %>
      <p class="help">What's your post about? Entertain us.</p>
      <div class="control">
        <%= f.text_area :content, rows: 12, class: "textarea" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.submit "Create", class: "button is-link" %>
      </div>
    </div>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class='container'>
  <%= link_to @forum, class: "button" do %>
    <p><%= fa_icon "arrow-left" %> See all posts in <%= @forum.name %></p>
  <% end %>

  <h1 class='title'><%= @post.title %></h1>
  <p><%= @post.content %></p>

  <hr />
  
  <button class="button">Add New Comment</button>
  <br />
  <% if @comments.size == 0 %>
    <p>No comments yet!</p>
  <% else %>
    <% @comments.each do |comment| %>
      <div class='card'>
        <div class='card-content'>
          <%= comment.content %>
          <p class='is-size-7'>
            Posted on <%= comment.created_at.to_formatted_s(:short) %>
            <% if comment.created_at != comment.updated_at %>
              , Last updated on <%= comment.updated_at.to_formatted_s(:short) %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>